### ISSUE TITLE
App install failing on QE43Q64BAUXXN

### ISSUE THREAD

**Issue by DeCodeerHeer** [gardner/jellyfin-tizen-build#4]
I am trying to install the package on my newly bought 43" Samsung QLED 2022 TV. However, upon installing the app to the TV, the CLI reports the following message.

```
tizen@eff58a01880f:/$ tizen install -n /output/Jellyfin.wgt
Transferring the package...
Transferred the package: /output/Jellyfin.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
java.lang.NullPointerException
	at org.tizen.ncli.util.ConfigXMLUtil.getAppID(ConfigXMLUtil.java:39)
	at org.tizen.ncli.subcommands.target.InstallCLICommand.getAppID(InstallCLICommand.java:424)
	at org.tizen.ncli.subcommands.target.InstallCLICommand.getTVInstallCmd(InstallCLICommand.java:375)
	at org.tizen.ncli.subcommands.target.InstallCLICommand.installPackage(InstallCLICommand.java:283)
	at org.tizen.ncli.subcommands.target.InstallCLICommand.call(InstallCLICommand.java:170)
	at org.tizen.ncli.subcommands.target.InstallCLICommand.call(InstallCLICommand.java:63)
	at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
	at org.tizen.ncli.ide.shell.InstallCLI.execute(InstallCLI.java:70)
	at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
	at org.tizen.ncli.ide.shell.Main.run(Main.java:189)
	at org.tizen.ncli.ide.shell.Main.main(Main.java:122)
--------------------
Platform log view
--------------------

Failed to install Tizen application.
Total time: 00:00:03.113
```

Any idea?

**Comment by sam5558** [comment]
Same issue for me.
```
tizen@a92483b355b3:/output$ tizen install -n Jellyfin.wgt -t UA43T5300AUXMV
Transferring the package...
Transferred the package: /output/Jellyfin.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
java.lang.NullPointerException
        at org.tizen.ncli.util.ConfigXMLUtil.getAppID(ConfigXMLUtil.java:39)
        at org.tizen.ncli.subcommands.target.InstallCLICommand.getAppID(InstallCLICommand.java:424)
        at org.tizen.ncli.subcommands.target.InstallCLICommand.getTVInstallCmd(InstallCLICommand.java:375)
        at org.tizen.ncli.subcommands.target.InstallCLICommand.installPackage(InstallCLICommand.java:283)
        at org.tizen.ncli.subcommands.target.InstallCLICommand.call(InstallCLICommand.java:170)
        at org.tizen.ncli.subcommands.target.InstallCLICommand.call(InstallCLICommand.java:63)
        at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
        at org.tizen.ncli.ide.shell.InstallCLI.execute(InstallCLI.java:70)
        at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
        at org.tizen.ncli.ide.shell.Main.run(Main.java:189)
        at org.tizen.ncli.ide.shell.Main.main(Main.java:122)
--------------------
Platform log view
--------------------

Failed to install Tizen application.
Total time: 00:00:07.307
```
Any idea @gardner ?

**Comment by gardner** [comment]
You'd need to find the sdb version number then look in the source code to determine what is causing the null pointer exception: https://review.tizen.org/git/

You could try passing more arguments to the install command. It looks like it's looking for an AppID.
